/**
 * Entry points for importing Pathbuilder 2e characters into Wanderer's Guide.
 *
 * The share ID carries editor selections and Custom Files; the separately
 * generated official JSON export ID carries Pathbuilder's calculated build.
 * Keep these identifiers distinct and require the calculated build if supplied.
 */

import { Character } from '@schemas/content';
import { showNotification } from '@mantine/notifications';

import { extractBuildId } from './fetch-pathbuilder-share';
import { importFromPathbuilderShare } from './pathbuilder-share-importer';

export async function importFromPathbuilder(pathbuilderInput: string | number): Promise<Character | null> {
  const result = await importFromPathbuilderShare(pathbuilderInput);

  if (!result.ok) {
    console.error(`Pathbuilder import failed: ${result.error}`);
    return null;
  }

  if (result.warnings.length > 0) {
    console.warn(`Pathbuilder import left ${result.warnings.length} detail(s) unmapped:`, result.warnings);
  }

  return result.character;
}

/**
 * Import shared editor data together with the calculated JSON retrieved using
 * the ID generated by Pathbuilder's official Export → Export JSON action.
 */
export async function importFromPathbuilderWithExportId(
  pathbuilderInput: string | number,
  jsonExportIdInput: string
): Promise<Character | null> {
  const shareId = extractBuildId(pathbuilderInput);
  const jsonExportId = jsonExportIdInput.trim();

  if (!shareId) {
    showNotification({
      title: 'Pathbuilder import failed',
      message: 'Enter a valid Pathbuilder share ID or link.',
      color: 'red',
      autoClose: false,
    });
    return null;
  }

  if (!/^\d{1,12}$/.test(jsonExportId)) {
    showNotification({
      title: 'Pathbuilder import failed',
      message: 'Enter the numeric ID generated by Pathbuilder’s Export → Export JSON action.',
      color: 'red',
      autoClose: false,
    });
    return null;
  }

  const result = await importFromPathbuilderShare(pathbuilderInput, { derivedBuildId: jsonExportId });
  if (!result.ok) {
    console.error(`Pathbuilder import with JSON export ID failed: ${result.error}`);
    return null;
  }

  if (result.warnings.length > 0) {
    console.warn('Pathbuilder import left unmapped details:', result.warnings);
  }
  return result.character;
}

export { importFromPathbuilderShare };
export type { PathbuilderImportOutcome } from './pathbuilder-share-importer';
