/**
 * Entry points for importing Pathbuilder 2e characters into Wanderer's Guide.
 *
 * The share ID carries editor selections and Custom Files; the separately
 * generated official JSON export ID carries Pathbuilder's calculated build.
 * Required WG choices are preflighted before any character or custom-content rows
 * are written. If a choice is missing, the caller can collect it and run preflight again.
 */

import { Character } from '@schemas/content';
import { showNotification } from '@mantine/notifications';

import { extractBuildId } from './fetch-pathbuilder-share';
import {
  importFromPathbuilderShare,
  preflightPathbuilderImport,
  PathbuilderSelectionPrompt,
} from './pathbuilder-share-importer';

export type PathbuilderInteractiveImportResult =
  | { status: 'selection-required'; selection: PathbuilderSelectionPrompt }
  | { status: 'imported'; character: Character }
  | { status: 'failed' };

export async function importFromPathbuilder(pathbuilderInput: string | number): Promise<Character | null> {
  const result = await importFromPathbuilderShare(pathbuilderInput);

  if (!result.ok) {
    console.error(`Pathbuilder import failed: ${result.error}`);
    return null;
  }

  if (result.warnings.length > 0) {
    console.warn(`Pathbuilder import left ${result.warnings.length} detail(s) unmapped:`, result.warnings);
  }

  return result.character;
}

/**
 * First resolve every required operation choice without making persistent changes.
 * Missing choices are returned to the UI one at a time because later choices may
 * depend on earlier selections. Only after preflight is complete does character
 * creation and custom-content persistence begin.
 */
export async function importFromPathbuilderWithExportId(
  pathbuilderInput: string | number,
  jsonExportIdInput: string,
  selectionOverrides: Record<string, string> = {}
): Promise<PathbuilderInteractiveImportResult> {
  const shareId = extractBuildId(pathbuilderInput);
  const jsonExportId = jsonExportIdInput.trim();

  if (!shareId) {
    showNotification({
      title: 'Pathbuilder import failed',
      message: 'Enter a valid Pathbuilder share ID or link.',
      color: 'red',
      autoClose: false,
    });
    return { status: 'failed' };
  }

  if (!/^\d{1,12}$/.test(jsonExportId)) {
    showNotification({
      title: 'Pathbuilder import failed',
      message: 'Enter the numeric ID generated by Pathbuilder’s Export → Export JSON action.',
      color: 'red',
      autoClose: false,
    });
    return { status: 'failed' };
  }

  const preflight = await preflightPathbuilderImport(pathbuilderInput, {
    derivedBuildId: jsonExportId,
    selectionOverrides,
  });
  if (preflight.status === 'selection-required') {
    return preflight;
  }
  if (preflight.status === 'error') {
    showNotification({
      title: 'Pathbuilder import could not continue',
      message: preflight.error,
      color: 'red',
      autoClose: false,
    });
    return { status: 'failed' };
  }

  const result = await importFromPathbuilderShare(pathbuilderInput, {
    derivedBuildId: jsonExportId,
    selectionOverrides,
  });
  if (!result.ok) {
    console.error(`Pathbuilder import with JSON export ID failed: ${result.error}`);
    return { status: 'failed' };
  }

  if (result.warnings.length > 0) {
    console.warn('Pathbuilder import left unmapped details:', result.warnings);
  }
  return { status: 'imported', character: result.character };
}

export { importFromPathbuilderShare };
export type { PathbuilderImportOutcome } from './pathbuilder-share-importer';
