-- Pathbuilder 2e share-link import provenance.
--
-- The 1:1 importer (frontend/src/process/import/pathbuilder/) keeps the exact
-- payload Pathbuilder handed it, so a character can be re-translated later
-- (WG -> PT-BR, WG -> Pathbuilder, or a re-run after a mapping fix) without
-- asking the user for the share link again.
--
-- This is deliberately NOT stored in character.meta_data: that column is part of
-- the character document and is rewritten on every character save, so a ~100 KB
-- Pathbuilder snapshot would be round-tripped through the API on every edit.
--
-- Re-runnable, per the invariant in docs/docker.md: migrations replay over a
-- schema that may already contain them.

create table if not exists public.pathbuilder_import (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  character_id bigint,
  -- Pathbuilder's emailedBuildID. Text, not bigint: it is an opaque external id
  -- and the constraint below is what keeps it sane.
  build_id text not null check (build_id ~ '^[0-9]+$'),
  source_url text,
  -- Pathbuilder's `version` field (e.g. "121"). This is the *data format*
  -- version, not the web app version. The adapter is selected on it.
  format_version text,
  imported_at timestamptz not null default now(),
  -- characterData, verbatim.
  character_data jsonb not null,
  -- listCustomFiles, verbatim. Each entry's `json` stays a string, exactly as
  -- Pathbuilder sent it (its escape depth is inconsistent between file types).
  custom_files jsonb not null default '[]'::jsonb,
  -- The derived json.php payload, when that endpoint was reachable. Null is the
  -- normal case for shared builds.
  derived_data jsonb,
  -- Everything the importer could not resolve, each with a reason. Surfaced to
  -- the user after import and kept for debugging the adapter.
  unresolved jsonb not null default '[]'::jsonb
);

alter table public.pathbuilder_import
  drop constraint if exists pathbuilder_import_character_id_fkey;
alter table public.pathbuilder_import
  add constraint pathbuilder_import_character_id_fkey
  foreign key (character_id) references public."character"(id) on delete cascade;

create index if not exists pathbuilder_import_user_id_idx on public.pathbuilder_import (user_id);
create index if not exists pathbuilder_import_character_id_idx on public.pathbuilder_import (character_id);
create index if not exists pathbuilder_import_build_id_idx on public.pathbuilder_import (build_id);

alter table public.pathbuilder_import enable row level security;

-- Private by design: a snapshot is a full copy of someone's character, and
-- characters have their own visibility rules (options->'is_public'). Inheriting
-- those here would let a public character leak another user's import history.
revoke all on public.pathbuilder_import from public;
revoke all on public.pathbuilder_import from anon;

-- The snapshot API is the sole write path. Authenticated clients may read their
-- own snapshot history, but inserts/updates/deletes are service-role operations
-- performed only after connect() has validated the caller's session.
grant select on public.pathbuilder_import to authenticated;
grant all on public.pathbuilder_import to service_role;

drop policy if exists "pathbuilder_import_select_own" on public.pathbuilder_import;
create policy "pathbuilder_import_select_own" on public.pathbuilder_import
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "pathbuilder_import_insert_own" on public.pathbuilder_import;
drop policy if exists "pathbuilder_import_update_own" on public.pathbuilder_import;
drop policy if exists "pathbuilder_import_delete_own" on public.pathbuilder_import;

comment on table public.pathbuilder_import is
  'Raw Pathbuilder 2e share-link payloads, kept so an imported character can be re-translated without re-fetching.';
